[WIP] Rust circuit
axiom-crypto/axiom-kwenta-incentives pull request #3
Opened 2024-04-25 02:44 UTC by ytham

- Rust circuit (WIP)
- Needs test still

2024-04-25 03:29 UTC, yi-sun requested changes

2024-04-25 03:29 UTC, yi-sun commented on app/kwenta-circuit/src/claim.rs
> +    pub executor_fees: FixLenVec<usize, MAX_INPUTS>,
Is this extraneous?

2024-04-25 03:29 UTC, yi-sun commented on app/kwenta-circuit/src/claim.rs
> +            let event_contract_or_zero = gate.or(api.ctx(), event_contract_is_equal, is_out_of_range);
Should this be `event_contract_or_one`?

2024-04-25 03:29 UTC, yi-sun commented on app/kwenta-circuit/src/claim.rs
> +                let account_id_or_zero = gate.or(api.ctx(), account_id_is_equal, is_out_of_range);
`account_id_or_one`

2024-04-25 03:29 UTC, yi-sun commented on app/kwenta-circuit/src/claim.rs
> +
`account_id` missing?

2024-04-26 16:50 UTC, ytham commented
@yi-sun ready for re-review

2024-04-26 21:54 UTC, yi-sun approved these changes
LGTM!

2024-04-26 21:54 UTC, merged